[[redirects]]
from = "https://discord.sobal.fi/*"
to = "https://discord.gg/sobal"
status = 200
force = true

[[redirects]]
from = "https://api-v3.sobal.fi/*"
to = "https://bl5ot3alqvc77hllxgclj72rmm.appsync-api.eu-north-1.amazonaws.com/:splat"
force = true
headers = {X-Api-Key = "da2-7v6khhpxwbfm3hzoofmenop4sa"}
