[[redirects]]
from = "https://discord.sobal.fi/*"
to = "https://discord.gg/sobal"
status = 200
force = true

[[redirects]]
from = "https://api-v3.sobal.fi/*"
to = "https://api-v3.balancer.fi/:splat"
status = 200
force = true
