[[redirects]]
from = "https://discord.sobal.fi/*"
to = "https://discord.gg/pMVUEM3bn9" # revert to https://discord.gg/sobal when boosted
status = 200
force = true

[[redirects]]
from = "https://sobal.fi/*"
to = "https://app.sobal.fi/"
status = 301
force = true

[[redirects]]
from = "https://www.sobal.fi/*"
to = "https://app.sobal.fi/"
status = 301
force = true